{% set version = "1.6.0" %}

package:
  name: pytest-forked
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-forked/pytest-forked-{{ version }}.tar.gz
  sha256: 4dafd46a9a600f65d822b8f605133ecf5b3e1941ebb3588e943b4e3eb71a5a3f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pytest >=3.10
    - py

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_forked
  files:
    - dummy_test.py
  commands:
    - pytest --forked dummy_test.py

about:
  home: https://github.com/pytest-dev/pytest-forked
  license: MIT
  license_file: LICENSE
  summary: run tests in isolated forked subprocesses
  dev_url: https://github.com/pytest-dev/pytest-forked

extra:
  recipe-maintainers:
    - nicoddemus
