{% set version = "1.1.1" %}

package:
  name: pytest-forked
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-forked/pytest-forked-{{ version }}.tar.gz
  sha256: e2d46f319c8063a3a0536b18f9cdea6eea3bc9fe2cb16c94e1d6fad3abc37300

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pytest >=2.6.0
    - setuptools_scm
  run:
    - python
    - pytest >=2.6.0

test:
  imports:
    - pytest_forked
  files:
    - dummy_test.py
  commands:
    - py.test --forked dummy_test.py  # [not win]

about:
  home: https://github.com/pytest-dev/pytest-forked
  license: MIT
  license_file: LICENSE
  summary: 'run tests in isolated forked subprocesses'
  dev_url: https://github.com/pytest-dev/pytest-forked

extra:
  recipe-maintainers:
    - nicoddemus
