{% set version = "1.4.0" %}

package:
  name: pytest-forked
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-forked/pytest-forked-{{ version }}.tar.gz
  sha256: 8b67587c8f98cbbadfdd804539ed5455b6ed03802203485dd2f53c1422d7440e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - pytest >=3.10
    - py

test:
  imports:
    - pytest_forked
  files:
    - dummy_test.py
  commands:
    - pytest --forked dummy_test.py

about:
  home: https://github.com/pytest-dev/pytest-forked
  license: MIT
  license_file: LICENSE
  summary: run tests in isolated forked subprocesses
  dev_url: https://github.com/pytest-dev/pytest-forked

extra:
  recipe-maintainers:
    - nicoddemus
